version: '3.1'
services:
  node-1:
    container_name: node-1
    build: ./node-1
    ports:
      - 3000:3000
    networks:
      - inbound
      - outbound
  node-2:
    container_name: node-2
    build: ./node-2
    ports:
      - 3001:3000
    networks:
      - inbound
      - outbound
networks:
  inbound:
    # external: true
    driver: bridge
    name: project-1_inbound
  outbound:
    external: true
    name: outbound